server:
  port: 9035
spring:
  application:
    name: cloud-gateway-eureka
  redis:
    host: localhost
    password: 123456
    port: 6379
  cloud:
    gateway:
      enabled: true
      routes:
#      一定要加 -
      - id: gateway_route
        uri: https://www.baidu.com
#        路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
        predicates:
        - Path=/more

#      一定要加 -
      - id: gateway_route2
        uri: http://localhost:9010
#        路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
        predicates:
        - Path=/paramProduct
        filters:
        - AddRequestParameter=param, test
        - name: RequestRateLimiter
          args:
            #姑且加个备注，看清开头是redis，所以一定要！！！配置redis
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
#            rate-limiter: "#{@rateLimiter}"
            key-resolver: "#{@apiKeyResolver}"
      #服务发现并注册
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9000/eureka/,http://eureka2:9001/eureka/,http://eureka3:9002/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
