spring:
  application:
    name: spring-cloud-zuul
server:
  port: 9030

#这里的配置表示，访问/test/** 直接重定向到http://localhost:9020/**
#test是自定义链路
zuul:
  routes:
    test:
      path: /test/**
      url: http://localhost:9020/
    #    serviceId: users_service
    autoTest:
      path: /**
      url: http://localhost:9020/clientFeign/
    #    serviceId: users_service
    proxyTest:
      path: /feign/**
      serviceId: spring-cloud-consumer

    proxyTest2:
      path: /product/**
      serviceId: spring-cloud-producer
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Methods

eureka:
  client:
    service-url:
      defaultZone: http://test:123456@eureka1:9000/eureka/,http://test:123456@eureka2:9001/eureka/,http://test:123456@eureka3:9002/eureka/