
server:
  port: 9000
spring:
  application:
    name: spring-cloud-eureka
  security:
    user:
      name: test
      password: 123456
      roles: CLIENT
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://test:123456@eureka2:9001/eureka/, http://test:123456@eureka3:9002/eureka/

---
spring:
  application:
    name: spring-cloud-eureka
  security:
    user:
      name: test
      password: 123456
      roles: CLIENT
  profiles: eureka2
server:
  port: 9001
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://test:123456@eureka1:9000/eureka/,http://test:123456@eureka3:9002/eureka/

---
server:
  port: 9002
spring:
  application:
    name: spring-cloud-eureka
    prefer-ip-address: true
  security:
    user:
      name: test
      password: 123456
      roles: CLIENT
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    service-url:
      defaultZone: http://test:123456@eureka1:9000/eureka/,http://test:123456@eureka2:9001/eureka/


##表示是否将自己注册到Eureka Server，默认为true。
#eureka.client.register-with-eureka=false
##表示是否从Eureka Server获取注册信息，默认为true
#eureka.client.fetch-registry=false
##设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
#eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/
