server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pirluoxue/MySpringCloud/
          search-paths: Config
          username:
          password:

  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 123456

#使用消息总线进行更新，需要使用eureka
eureka:
  client:
    service-url:
      defaultZone: http://test:123456@eureka1:9000/eureka/,http://test:123456@eureka2:9001/eureka/,http://test:123456@eureka3:9002/eureka/

#这个部分是2.x之后的配置方式，之前是management.security.enabled=false这样的
#总线刷新地址也就是http://localhost:8001/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


