spring:
  application:
    name: spring-cloud-consumer
server:
  port: 9020
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9000/eureka/,http://eureka2:9001/eureka/,http://eureka3:9002/eureka/
