spring:
  application:
    name: spring-cloud-consumer

server:
  port: 9020
eureka:
  client:
    service-url:
      defaultZone: http://test:123456@eureka1:9000/eureka/,http://test:123456@eureka2:9001/eureka/,http://test:123456@eureka3:9002/eureka/
feign:
  hystrix:
    enabled: true
